### ISSUE TITLE
Error no module named sklearn

### ISSUE THREAD

**Issue by jgmeyerucsd** [isayev/ReLeaSE#12]
The logp notebook throws an error trying to import what I think is scikit-learn

**Comment by Mariewelt** [comment]
@jgmeyerucsd Do you have scikit-learn installed?

**Comment by jgmeyerucsd** [comment]
I tried a different conda enviroment (fastai) and it worked - the first environment must not have had it installed

**Comment by Mariewelt** [comment]
You can install it yourself in any environment by running 
`conda install scikit-learn`
from the command line.
