### ISSUE TITLE
jak2_data.csv

### ISSUE THREAD

**Issue by wojiaolyj** [isayev/ReLeaSE#7]
can't find jak2_data.csv in the clone,How to get jak2_data.csv，

**Comment by isayev** [comment]
Hey, @wojiaolyj in the paper we used proprietary data, that cannot be shared. You could use JAK2 (CHEMBL ID 2971) dataset or any other target of your interest.

**Comment by wojiaolyj** [comment]
Do the following data and modules also need to be downloaded by myself? where to download？
1./home/yf302/mariewelt/Notebooks/PyTorch/data/egfr_with_pubchem.smi 
2.my_generator.load_model('/home/mariewelt/Notebooks/PyTorch/Model_checkpoints/generator/checkpoint_lstm')
3.egfr_predictor.load_model('/home/mariewelt/Notebooks/PyTorch/data/RF/EGFR_RF')

**Comment by Mariewelt** [comment]
Hi @wojiaolyj 

main.py file was put to the repository by mistake, thanks for pointing this out! I will remove it now, as it's not doing anything meaningful. We share ipython notebooks JAK2-demo.ipynb and LogP-demo.ipynb, that demonstrate how to run our algorithm. Data for LogP-demo.ipynb are available in the data folder. Unfortunately, we can't share jak2 data, but as has already been said, you can download dataset for this target (or any other target of your choice) from CHEMBL database.

**Comment by wojiaolyj** [comment]
Thank you very much for the data you uploaded. I successfully installed Rdkit once, and then I made an error when I executed the program，I reinstalled the system. After installing Rdkit, I always showed that the follow two tests failed. I tried many methods were not solved. Is related to cuda and cudnn?

98% tests passed, 2 tests failed out of 131

Total Test time (real) = 244.60 sec

The following tests FAILED:
	127 - pythonTestDirDbase (Failed)
	130 - pythonTestDirChem (Failed)
Errors while running CTest

**Comment by gmseabra** [comment]
I'm sorry for coming back to this issue, but is there a chance you guys could upload at least a *sample* file, just so we can see the full format expected?

Thanks!

**Comment by wojiaolyj** [comment]
This problem occurs when I run the program JAK2-demo, my cuda version is cuda9.0.

hidden_size = 1500
stack_width = 1500
stack_depth = 200
lr = 0.01
my_generator = StackAugmentedGRU(input_size=gen_data.n_characters, hidden_size=hidden_size,
                                 output_size=gen_data.n_characters, stack_width=stack_width,
                                 stack_depth=stack_depth, use_cuda=use_cuda, n_layers=1,
                                 optimizer='Adadelta', lr=lr)

if use_cuda:
    my_generator = my_generator.cuda()
------------------------------------------------------------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-17-027543faea9f> in <module>()
     12 
     13 if use_cuda:
---> 14     my_generator = my_generator.cuda()

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in cuda(self, device)
    256             Module: self
    257         """
--> 258         return self._apply(lambda t: t.cuda(device))
    259 
    260     def cpu(self):

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in _apply(self, fn)
    183     def _apply(self, fn):
    184         for module in self.children():
--> 185             module._apply(fn)
    186 
    187         for param in self._parameters.values():

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in _apply(self, fn)
    189                 # Tensors stored in modules are graph leaves, and we don't
    190                 # want to create copy nodes, so we have to unpack the data.
--> 191                 param.data = fn(param.data)
    192                 if param._grad is not None:
    193                     param._grad.data = fn(param._grad.data)

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in <lambda>(t)
    256             Module: self
    257         """
--> 258         return self._apply(lambda t: t.cuda(device))
    259 
    260     def cpu(self):

RuntimeError: CUDA error: unknown error
